import type { RuntimeAssetDefinition } from './assets.js';

// Generated by scripts/build-assets.mjs from assets/definitions/*.json.
export const GENERATED_ASSET_REGISTRY: readonly RuntimeAssetDefinition[] = Object.freeze([] as RuntimeAssetDefinition[]);
