import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { assertAllowedWritePath, assertInside, createStudioState, PRESENTATION_GENERATED_PATH, PRESENTATION_SOURCE_PATH, revertStudioChange, saveStructuredPresentationChange, validateAssetImportRequest } from '../tools/studio/server-core.mjs';
import { developmentContextForDesignTargetId, developmentContextForProp } from '../.test-dist/src/presentation/developmentContext.js';
import { createChangeReceipt, serializeChangeReceipt } from '../.test-dist/src/presentation/changeReceipt.js';
import { formatChangeReceipt } from '../.test-dist/src/presentation/changeReceiptExports.js';
import { clearAllPresentationPreviews, resolvePreviewRepresentation, setPresentationPreviewParameters } from '../.test-dist/src/presentation/previewOverrides.js';
import { MEDIUM_BUCKET_TARGET } from '../.test-dist/src/presentation/level0FeatureRepresentations.js';
const ROOT=process.cwd();
function git(root,args){const result=spawnSync('git',args,{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);}
function fixture(){const root=mkdtempSync(join(tmpdir(),'noclip-studio-'));mkdirSync(resolve(root,'src/presentation/definitions'),{recursive:true});mkdirSync(resolve(root,'src/presentation'),{recursive:true});writeFileSync(resolve(root,PRESENTATION_SOURCE_PATH),readFileSync(resolve(ROOT,PRESENTATION_SOURCE_PATH)));writeFileSync(resolve(root,PRESENTATION_GENERATED_PATH),'before generated\n');git(root,['init','-b','studio-test']);git(root,['config','user.email','studio@test.invalid']);git(root,['config','user.name','Studio Test']);git(root,['add','.']);git(root,['commit','-m','fixture']);return root;}
function canonicalStub(_root,action,payload){if(action==='context'){const context=developmentContextForDesignTargetId(payload.targetId,payload.options);assert.ok(context);return{context,json:JSON.stringify(context),human:'context',fullPrompt:'prompt'};}if(action==='receipt'){const receipt=createChangeReceipt(payload.context,payload.change);return{receipt,json:serializeChangeReceipt(receipt),human:formatChangeReceipt(receipt)};}throw new Error(`unexpected canonical action ${action}`);}
const validationStub=()=>({passed:true,validations:[{name:'fixture validation',status:'PASS',detail:'executed by test'}],targetedTests:['tests/studio-foundation.test.mjs'],deterministicIdentity:'PASS',saveCompatibility:'PASS',warnings:[]});const builderStub=(root)=>{writeFileSync(resolve(root,PRESENTATION_GENERATED_PATH),'after generated\n');return{status:0,stdout:'generated',stderr:''};};

test('Studio path policy rejects traversal and arbitrary source writes',()=>{const root=fixture();assert.throws(()=>assertInside(root,'../escape.txt'),/escapes/);assert.throws(()=>assertAllowedWritePath(root,'src/world/generator.ts'),/not allowed/);assert.doesNotThrow(()=>assertAllowedWritePath(root,PRESENTATION_SOURCE_PATH));});
test('runtime preview overrides are ephemeral and revert to canonical PAU values',()=>{clearAllPresentationPreviews();const before=resolvePreviewRepresentation(MEDIUM_BUCKET_TARGET);assert.equal(before.definition.parameters.topRadiusRatio,0.46);setPresentationPreviewParameters(MEDIUM_BUCKET_TARGET,{topRadiusRatio:0.475});assert.equal(resolvePreviewRepresentation(MEDIUM_BUCKET_TARGET).definition.parameters.topRadiusRatio,0.475);clearAllPresentationPreviews();assert.equal(resolvePreviewRepresentation(MEDIUM_BUCKET_TARGET).definition.parameters.topRadiusRatio,0.46);});
test('DevelopmentContext remains canonical and distinguishes design target from runtime instance',()=>{const design=developmentContextForDesignTargetId('feature.medium-bucket');assert.equal(design.schema,'development-context-v1');assert.equal(design.runtimeInstance,undefined);assert.equal(design.representation.id,'bucket.default');const descriptor={id:'cell:test',address:{worldSeed:'seed',generationVersion:'gen3-v1',cellX:2,cellZ:-1},world:{regionId:'arch-rooms',conditionIds:['deep-wet-carpet']}};const prop={id:'bucket:stable',kind:'bucket',position:{x:1,y:.3,z:2}};const runtime=developmentContextForProp(descriptor,prop);assert.equal(runtime.designTarget.semanticTargetId,'feature.medium-bucket');assert.equal(runtime.runtimeInstance.stableRuntimeId,'bucket:stable');assert.equal(runtime.runtimeInstance.regionId,'arch-rooms');assert.deepEqual(runtime.runtimeInstance.conditionIds,['deep-wet-carpet']);});
test('structured Save writes only canonical PAU source, records executed validation, and supports hash-guarded targeted revert',()=>{const root=fixture(),studio=createStudioState(root);const result=saveStructuredPresentationChange(studio,{targetId:'feature.medium-bucket',parameterPatch:{topRadiusRatio:0.465},observation:'pilot',requestedChange:'slightly widen upper radius'},{validationRunner:validationStub,presentationBuilder:builderStub,studioCompiler:()=>{},canonicalCaller:canonicalStub});const source=JSON.parse(readFileSync(resolve(root,PRESENTATION_SOURCE_PATH),'utf8'));assert.equal(source.representations.find((item)=>item.id==='bucket.default').parameters.topRadiusRatio,0.465);assert.equal(result.receipt.beforeValues.topRadiusRatio,0.46);assert.equal(result.receipt.afterValues.topRadiusRatio,0.465);assert.equal(result.receipt.validation[0].status,'PASS');assert.equal(result.receipt.deterministicIdentity,'PASS');revertStudioChange(studio,result.id,{studioCompiler:()=>{}});const reverted=JSON.parse(readFileSync(resolve(root,PRESENTATION_SOURCE_PATH),'utf8'));assert.equal(reverted.representations.find((item)=>item.id==='bucket.default').parameters.topRadiusRatio,0.46);});
test('Studio refuses to overwrite a canonical source file that was dirty before Studio started',()=>{const root=fixture(),path=resolve(root,PRESENTATION_SOURCE_PATH);writeFileSync(path,readFileSync(path,'utf8').replace('0.46','0.47'));const studio=createStudioState(root);assert.throws(()=>saveStructuredPresentationChange(studio,{targetId:'feature.medium-bucket',parameterPatch:{topRadiusRatio:0.465}},{validationRunner:validationStub,presentationBuilder:builderStub,studioCompiler:()=>{},canonicalCaller:canonicalStub}),/pre-existing worktree changes/);});
test('asset import request validation rejects code, wrong profiles, and unsafe semantic IDs',()=>{const profiles=[{id:'Wall Texture',type:'image',roles:['wall-texture']},{id:'Feature Mesh',type:'mesh',roles:['feature-mesh']}];assert.throws(()=>validateAssetImportRequest({assetId:'../bad',profile:'Wall Texture',fileName:'x.png',dataBase64:'YQ=='},profiles),/Asset ID/);assert.throws(()=>validateAssetImportRequest({assetId:'level0.asset.test',profile:'Feature Mesh',fileName:'payload.js',dataBase64:'YQ=='},profiles),/does not accept/);assert.equal(validateAssetImportRequest({assetId:'level0.wallpaper.test',profile:'Wall Texture',fileName:'wall.png',dataBase64:'YQ=='},profiles).profile.type,'image');});
test('World Lab Studio integration stays semantic and production main gates the bridge behind import.meta.env.DEV',()=>{const worldLab=readFileSync('src/dev/worldLabStudioIntegration.ts','utf8'),main=readFileSync('src/main.ts','utf8');assert.match(worldLab,/Open in Studio/);assert.match(worldLab,/STUDIO_TARGETS/);assert.match(worldLab,/WORLD_LAB_STUDIO_EVENT/);assert.match(main,/if \(import\.meta\.env\.DEV\)/);assert.match(main,/import\('\.\/dev\/studioBridgeClient\.js'\)/);assert.ok(!main.includes('tools/studio/server'));});
