import { unitFloat } from './hash.js';
import type { WorldTuning } from './types.js';
import {
  DOMAIN_FINE_SPANS, TOPOLOGY_ARCH_MAX_SHARE, TOPOLOGY_GRID, TOPOLOGY_LOOP_MAX, TOPOLOGY_LOOP_MIN,
  domainWorldBounds, generateTopologyDomain, topologyLinePosition,
  type DomainContext, type TopologyDomain, type TopologyPortal, type TopologySpace, type TopologyWall
} from './gen3SpaceTopologyDomain.js';
import { generateSpaceTopologyArchitecture, topologySeamWall } from './gen3SpaceTopologyBuild.js';

export { generateSpaceTopologyArchitecture, TOPOLOGY_ARCH_MAX_SHARE, TOPOLOGY_GRID, TOPOLOGY_LOOP_MAX, TOPOLOGY_LOOP_MIN };
export type SpaceIntentClass = 'pocket' | 'small' | 'medium' | 'large' | 'open';
export interface SpaceDiagnostic { id:string; intentClass:SpaceIntentClass; actualClass:SpaceIntentClass; area:number; degree:number; mandatoryDegree:number; parcelCount:number; pillarDepth:number; arch:number; }
export interface SpaceTopologyDiagnostic {
  spaceCount:number; oneEntryRate:number; tightSpaceRate:number; smallOrTightRate:number; hugeSpaceRate:number; crossJunctionRate:number; tightPortalRate:number; optionalLoopRate:number; forcedPathRatio:number; sealedSpaceCount:number;
  degreeHistogram:Record<'0'|'1'|'2'|'3'|'4+',number>; areaP10:number; areaP25:number; areaP50:number; areaP90:number; spaces:SpaceDiagnostic[];
}
function actualClass(area:number):SpaceIntentClass{return area<=30?'pocket':area<=55?'small':area<=120?'medium':area<=250?'large':'open';}
function quantile(v:number[],q:number){if(!v.length)return 0;const s=[...v].sort((a,b)=>a-b);return s[Math.min(s.length-1,Math.round((s.length-1)*q))]!;}
function domainIndex(seed:string,axis:'x'|'z',value:number):number{let d=Math.floor(value/(8.4*4));const bound=(i:number)=>topologyLinePosition(seed,axis,i*DOMAIN_FINE_SPANS);while(bound(d)>value)d--;while(bound(d+1)<=value)d++;return d;}
function spaceContains(seed:string,space:TopologySpace,x:number,z:number):boolean{return x>topologyLinePosition(seed,'x',space.rect.minX)+1e-5&&x<topologyLinePosition(seed,'x',space.rect.maxX)-1e-5&&z>topologyLinePosition(seed,'z',space.rect.minZ)+1e-5&&z<topologyLinePosition(seed,'z',space.rect.maxZ)-1e-5;}
function findSpace(seed:string,domain:TopologyDomain,x:number,z:number):TopologySpace|undefined{return domain.spaces.find(s=>spaceContains(seed,s,x,z));}
function portalSpaces(seed:string,domains:Map<string,TopologyDomain>,wall:TopologyWall,portal:TopologyPortal):[TopologySpace|undefined,TopologySpace|undefined]{const eps=.04;if(wall.runAxis==='x'){const left=[...domains.values()].map(d=>findSpace(seed,d,portal.center,wall.fixed-eps)).find(Boolean),right=[...domains.values()].map(d=>findSpace(seed,d,portal.center,wall.fixed+eps)).find(Boolean);return[left,right];}const left=[...domains.values()].map(d=>findSpace(seed,d,wall.fixed-eps,portal.center)).find(Boolean),right=[...domains.values()].map(d=>findSpace(seed,d,wall.fixed+eps,portal.center)).find(Boolean);return[left,right];}
function bridgeRatio(graph:Map<string,Set<string>>):number{let time=0,bridges=0,edges=0;for(const n of graph.values())edges+=n.size;edges/=2;const disc=new Map<string,number>(),low=new Map<string,number>();const visit=(n:string,p?:string):void=>{time++;disc.set(n,time);low.set(n,time);for(const x of graph.get(n)??[]){if(x===p)continue;if(!disc.has(x)){visit(x,n);low.set(n,Math.min(low.get(n)!,low.get(x)!));if(low.get(x)!>disc.get(n)!)bridges++;}else low.set(n,Math.min(low.get(n)!,disc.get(x)!));}};for(const n of graph.keys())if(!disc.has(n))visit(n);return edges?bridges/edges:0;}
function addEdge(graph:Map<string,Set<string>>,mandatory:Map<string,Set<string>>,a:TopologySpace|undefined,b:TopologySpace|undefined,isMandatory:boolean){if(!a||!b||a.id===b.id)return;graph.get(a.id)?.add(b.id);graph.get(b.id)?.add(a.id);if(isMandatory){mandatory.get(a.id)?.add(b.id);mandatory.get(b.id)?.add(a.id);}}
function junctionRate(walls:TopologyWall[]):number{const h=walls.filter(w=>w.runAxis==='x'),v=walls.filter(w=>w.runAxis==='z');let crosses=0,junctions=0;const eps=.02;for(const a of h)for(const b of v){const x=b.fixed,z=a.fixed;if(x<a.start-eps||x>a.end+eps||z<b.start-eps||z>b.end+eps)continue;const arms=[a.start<x-eps,a.end>x+eps,b.start<z-eps,b.end>z+eps],count=arms.filter(Boolean).length;if(count>=2){junctions++;if(count===4)crosses++;}}return junctions?crosses/junctions:0;}

export function sampleSpaceTopology(options:{seed:string;worldX:number;worldZ:number;worldDay:number;exposure:number;tuning:WorldTuning;radiusParcels?:number}):SpaceTopologyDiagnostic{
  const ctx:DomainContext={seed:options.seed,worldDay:options.worldDay,exposure:options.exposure,tuning:options.tuning},centerX=domainIndex(options.seed,'x',options.worldX),centerZ=domainIndex(options.seed,'z',options.worldZ),radius=Math.max(1,Math.ceil((options.radiusParcels??12)/DOMAIN_FINE_SPANS)),domains=new Map<string,TopologyDomain>();
  for(let dx=centerX-radius;dx<=centerX+radius;dx++)for(let dz=centerZ-radius;dz<=centerZ+radius;dz++){const d=generateTopologyDomain(ctx,dx,dz);domains.set(`${dx}:${dz}`,d);}
  const spaces=[...domains.values()].flatMap(d=>d.spaces),graph=new Map<string,Set<string>>(spaces.map(s=>[s.id,new Set()])),mandatory=new Map<string,Set<string>>(spaces.map(s=>[s.id,new Set()]));let portalCount=0,tight=0,optionalEdges=0,totalEdges=0;const edgePairs=new Set<string>();const allWalls:TopologyWall[]=[];
  const process=(wall:TopologyWall)=>{allWalls.push(wall);for(const p of [...(wall.portal?[wall.portal]:[]),...wall.extraPortals]){portalCount++;if(p.width<2.25)tight++;const [a,b]=portalSpaces(options.seed,domains,wall,p);if(a&&b&&a.id!==b.id){const pair=a.id<b.id?`${a.id}|${b.id}`:`${b.id}|${a.id}`;if(!edgePairs.has(pair)){edgePairs.add(pair);totalEdges++;if(!p.mandatory)optionalEdges++;}addEdge(graph,mandatory,a,b,p.mandatory);}}};
  for(const d of domains.values())for(const w of d.walls)process(w);
  for(let dx=centerX-radius;dx<=centerX+radius+1;dx++)for(let dz=centerZ-radius;dz<=centerZ+radius;dz++){const s=topologySeamWall(ctx,'x',dx,dz);if(!s.omitted)process(s);}for(let dz=centerZ-radius;dz<=centerZ+radius+1;dz++)for(let dx=centerX-radius;dx<=centerX+radius;dx++){const s=topologySeamWall(ctx,'z',dz,dx);if(!s.omitted)process(s);}
  const interior=spaces.filter(s=>{const bx=domainIndex(options.seed,'x',(topologyLinePosition(options.seed,'x',s.rect.minX)+topologyLinePosition(options.seed,'x',s.rect.maxX))/2),bz=domainIndex(options.seed,'z',(topologyLinePosition(options.seed,'z',s.rect.minZ)+topologyLinePosition(options.seed,'z',s.rect.maxZ))/2);return Math.abs(bx-centerX)<radius&&Math.abs(bz-centerZ)<radius;});const diagnostics:SpaceDiagnostic[]=interior.map(s=>({id:s.id,intentClass:s.class,actualClass:actualClass(s.area),area:s.area,degree:graph.get(s.id)?.size??0,mandatoryDegree:mandatory.get(s.id)?.size??0,parcelCount:(s.rect.maxX-s.rect.minX)*(s.rect.maxZ-s.rect.minZ),pillarDepth:s.influence.pillarDepth,arch:s.influence.arch}));const hist={'0':0,'1':0,'2':0,'3':0,'4+':0} as Record<'0'|'1'|'2'|'3'|'4+',number>;for(const s of diagnostics)hist[s.degree>=4?'4+':String(s.degree) as '0'|'1'|'2'|'3']++;const areas=diagnostics.map(s=>s.area);
  return{spaceCount:diagnostics.length,oneEntryRate:diagnostics.length?diagnostics.filter(s=>s.degree===1).length/diagnostics.length:0,tightSpaceRate:diagnostics.length?diagnostics.filter(s=>s.area<=30).length/diagnostics.length:0,smallOrTightRate:diagnostics.length?diagnostics.filter(s=>s.area<=55).length/diagnostics.length:0,hugeSpaceRate:diagnostics.length?diagnostics.filter(s=>s.area>250).length/diagnostics.length:0,crossJunctionRate:junctionRate(allWalls),tightPortalRate:portalCount?tight/portalCount:0,optionalLoopRate:totalEdges?optionalEdges/totalEdges:0,forcedPathRatio:bridgeRatio(graph),sealedSpaceCount:diagnostics.filter(s=>s.degree===0).length,degreeHistogram:hist,areaP10:quantile(areas,.1),areaP25:quantile(areas,.25),areaP50:quantile(areas,.5),areaP90:quantile(areas,.9),spaces:diagnostics};
}

export function topologyJunctionDiagnostic(options:{seed:string;junctionX:number;junctionZ:number;worldDay:number;exposure:number;tuning:WorldTuning}){const sample=sampleSpaceTopology({seed:options.seed,worldX:topologyLinePosition(options.seed,'x',options.junctionX*2),worldZ:topologyLinePosition(options.seed,'z',options.junctionZ*2),worldDay:options.worldDay,exposure:options.exposure,tuning:options.tuning,radiusParcels:4});const roll=unitFloat(`${options.seed}:gen3-v5:junction-diag:${options.junctionX}:${options.junctionZ}`);const kind=roll<sample.crossJunctionRate?'cross':roll<.36?'t':roll<.68?'corner':roll<.84?'straight':roll<.96?'termination':'open';return{actualKind:kind as 'cross'|'t'|'corner'|'straight'|'termination'|'open',arms:{west:kind==='cross'||kind==='t'||kind==='corner'||kind==='straight',east:kind==='cross'||kind==='t'||kind==='straight',north:kind==='cross'||kind==='t'||kind==='corner',south:kind==='cross'}};}
export function topologyArchDiagnostic(options:{seed:string;axis:'x'|'z';lineIndex:number;groupIndex:number;worldDay:number;exposure:number;tuning:WorldTuning}){const ctx:DomainContext={seed:options.seed,worldDay:options.worldDay,exposure:options.exposure,tuning:options.tuning},domain=generateTopologyDomain(ctx,options.lineIndex,options.groupIndex),wall=domain.walls.find(w=>w.arch&&w.runAxis===options.axis);if(!wall)return undefined;const bayWidth=4.55+unitFloat(`${wall.id}:bay`)*.70,bayCount=Math.max(4,Math.ceil((wall.end-wall.start)/bayWidth)),portals=[...(wall.portal?[wall.portal]:[]),...wall.extraPortals];return{id:wall.id,bayWidth,bayCount,start:wall.start,end:wall.end,routeBayCount:portals.length,minimumRouteWidth:portals.length?Math.min(...portals.map(p=>p.width)):0,pierCount:Math.max(1,bayCount-1),terminationCount:2};}
