import { unitFloat, stableId } from './hash.js';
import { CELL_SIZE, WALL_HEIGHT, WALL_THICKNESS, type MaterialId, type PropSpec, type WallSpec, type WorldTuning } from './types.js';
import { ARCH_HEADER_HEIGHT, ARCH_LOWER_HEIGHT, ARCH_PIER_WIDTH, PILLAR_MAX_WIDTH, PILLAR_MIN_WIDTH, PILLAR_SPACING, pushClippedWall, sampleGen3RegionInfluence, subtractIntervals, type Gen3ArchitectureResult } from './gen3ArchitectureCore.js';
import { DOMAIN_FINE_SPANS, DOMAIN_MAJOR_SPANS, TOPOLOGY_ARCH_MAX_SHARE, domainParent, domainWorldBounds, generateTopologyDomainSlice, sameDomain, topologyLinePosition, type DomainContext, type TopologyPortal, type TopologyWall } from './gen3SpaceTopologyDomain.js';

interface SeamWall extends TopologyWall { omitted:boolean; }
function clamp01(v:number){return Math.max(0,Math.min(1,v));}
function portalWidth(seed:string,key:string,length:number){const r=unitFloat(`${seed}:seam-kind:${key}`),w=unitFloat(`${seed}:seam-width:${key}`);let kind:TopologyPortal['kind'],width:number;if(r<.2){kind='tight';width=2.0+w*.25}else if(r<.75){kind='normal';width=2.25+w*.60}else if(r<.85){kind='wide';width=2.85+w*.60}else{kind='exceptional';width=3.45+w*.75}return{kind,width:Math.min(width,Math.max(1.45,length-.9))};}
export function topologySeamWall(ctx:DomainContext,boundaryAxis:'x'|'z',line:number,alongDomain:number):SeamWall{
  const vertical=boundaryAxis==='x';const left=vertical?{x:line-1,z:alongDomain}:{x:alongDomain,z:line-1};const right=vertical?{x:line,z:alongDomain}:{x:alongDomain,z:line};
  const fixed=topologyLinePosition(ctx.seed,vertical?'x':'z',line*DOMAIN_FINE_SPANS);const start=topologyLinePosition(ctx.seed,vertical?'z':'x',alongDomain*DOMAIN_FINE_SPANS);const end=topologyLinePosition(ctx.seed,vertical?'z':'x',(alongDomain+1)*DOMAIN_FINE_SPANS);const mid=(start+end)/2;const wx=vertical?fixed:mid,wz=vertical?mid:fixed;const inf=sampleGen3RegionInfluence(ctx.seed,wx,wz,ctx.worldDay,ctx.exposure,ctx.tuning);const key=`seam:${boundaryAxis}:${line}:${alongDomain}`;
  const parentLeft=domainParent(ctx.seed,left),parentRight=domainParent(ctx.seed,right);const mandatory=sameDomain(parentLeft,right)||sameDomain(parentRight,left);const omitted=inf.pillarDepth>.55&&unitFloat(`${ctx.seed}:gen3-v5:pillar-seam-open:${key}`)<clamp01((inf.pillarDepth-.55)/.45*.94);
  const length=end-start,connected=mandatory||unitFloat(`${ctx.seed}:gen3-v5:seam-connect:${key}`)<.85,pw=portalWidth(ctx.seed,key,length),margin=pw.width/2+.7,available=Math.max(0,length-margin*2),center=available>0?start+margin+available*(.18+unitFloat(`${ctx.seed}:gen3-v5:seam-center:${key}`)*.64):(start+end)/2;const portal:TopologyPortal|undefined=connected?{id:stableId('gen3-v5-seam-portal',ctx.seed,key),kind:pw.kind,width:pw.width,center,mandatory}:undefined;const extraPortals:TopologyPortal[]=[];
  const optionalChance=mandatory?.22:.14;if(connected&&portal&&unitFloat(`${ctx.seed}:gen3-v5:seam-extra:${key}`)<optionalChance){const ew=portalWidth(ctx.seed,`${key}:extra`,length),ec=start+length*(unitFloat(`${ctx.seed}:gen3-v5:seam-extra-center:${key}`)<.5?.30:.70);if(Math.abs(ec-center)>ew.width+pw.width/2+1.5)extraPortals.push({id:stableId('gen3-v5-seam-portal',ctx.seed,`${key}:extra`),kind:ew.kind,width:ew.width,center:Math.max(start+ew.width/2+.5,Math.min(end-ew.width/2-.5,ec)),mandatory:false});}
  const materialId:MaterialId=inf.arch>.28?'arch-pale-wallpaper':'level-0-wallpaper';return{id:stableId('gen3-v5-seam',ctx.seed,key),runAxis:vertical?'z':'x',fixed,start,end,portal,extraPortals,arch:false,materialId,omitted:omitted&&!mandatory};
}
function alignArchPortal(wall:TopologyWall,portal:TopologyPortal):TopologyPortal{const bay=4.55+unitFloat(`${wall.id}:bay`)*.70;const phase=wall.start+bay/2;const n=Math.round((portal.center-phase)/bay);const center=Math.max(wall.start+portal.width/2+.35,Math.min(wall.end-portal.width/2-.35,phase+n*bay));return{...portal,center};}
function addArchWall(output:WallSpec[],ctx:DomainContext,cellX:number,cellZ:number,wall:TopologyWall,pillarCuts:readonly [number,number][]):void{
  const portals=[...(wall.portal?[wall.portal]:[]),...wall.extraPortals].map(p=>alignArchPortal(wall,p));const routeCuts=portals.map(p=>[p.center-p.width/2,p.center+p.width/2] as [number,number]);const add=(id:string,start:number,end:number,y:number,height:number,cuts:readonly [number,number][])=>{for(const [a,b] of subtractIntervals(start,end,[...cuts,...pillarCuts]))pushClippedWall(output,ctx.seed,cellX,cellZ,`${wall.id}:${id}`,wall.runAxis,wall.fixed,a,b,y,height,'arch-pale-wallpaper');};
  add('lower',wall.start,wall.end,ARCH_LOWER_HEIGHT/2,ARCH_LOWER_HEIGHT,routeCuts);add('header',wall.start,wall.end,WALL_HEIGHT-ARCH_HEADER_HEIGHT/2,ARCH_HEADER_HEIGHT,[]);const bay=4.55+unitFloat(`${wall.id}:bay`)*.70,phase=wall.start;const pierH=WALL_HEIGHT-ARCH_HEADER_HEIGHT-ARCH_LOWER_HEIGHT,pierY=ARCH_LOWER_HEIGHT+pierH/2;
  let pi=0;for(let c=phase;c<=wall.end+bay;c+=bay){if(c+ARCH_PIER_WIDTH/2<=wall.start||c-ARCH_PIER_WIDTH/2>=wall.end)continue;add(`pier:${pi}`,c-ARCH_PIER_WIDTH/2,c+ARCH_PIER_WIDTH/2,pierY,pierH,[]);const sh=Math.min(.52,bay*.11);add(`shoulder-l:${pi}`,c-ARCH_PIER_WIDTH/2-sh,c-ARCH_PIER_WIDTH/2,2.49,.34,[]);add(`shoulder-r:${pi}`,c+ARCH_PIER_WIDTH/2,c+ARCH_PIER_WIDTH/2+sh,2.49,.34,[]);pi++;}
  const term=Math.min(.56,(wall.end-wall.start)*.08);add('term-start',wall.start,wall.start+term,WALL_HEIGHT/2,WALL_HEIGHT,[]);add('term-end',wall.end-term,wall.end,WALL_HEIGHT/2,WALL_HEIGHT,[]);
}
function pillarCutsForWall(cellX:number,cellZ:number,wall:TopologyWall,pillars:readonly PropSpec[]):Array<[number,number]>{const cx=cellX*CELL_SIZE,cz=cellZ*CELL_SIZE,cuts:Array<[number,number]>=[];for(const p of pillars){if(p.kind!=='column')continue;const wx=cx+p.position.x,wz=cz+p.position.z,hx=p.scale.x/2+WALL_THICKNESS/2+.12,hz=p.scale.z/2+WALL_THICKNESS/2+.12;if(wall.runAxis==='x'){if(Math.abs(wz-wall.fixed)>hz||wx+hx<=wall.start||wx-hx>=wall.end)continue;cuts.push([wx-hx,wx+hx]);}else{if(Math.abs(wx-wall.fixed)>hx||wz+hz<=wall.start||wz-hz>=wall.end)continue;cuts.push([wz-hz,wz+hz]);}}return cuts;}

function portalLandingCuts(target:TopologyWall,allWalls:readonly TopologyWall[]):Array<[number,number]>{
  const cuts:Array<[number,number]>=[];const landing=2.0;
  for(const source of allWalls){if(source.id===target.id||source.runAxis===target.runAxis)continue;for(const portal of [...(source.portal?[source.portal]:[]),...source.extraPortals]){
    if(target.runAxis==='x'){
      if(Math.abs(target.fixed-portal.center)>portal.width/2+.48||source.fixed<target.start-.02||source.fixed>target.end+.02)continue;
      cuts.push([source.fixed-landing,source.fixed+landing]);
    }else{
      if(Math.abs(target.fixed-portal.center)>portal.width/2+.48||source.fixed<target.start-.02||source.fixed>target.end+.02)continue;
      cuts.push([source.fixed-landing,source.fixed+landing]);
    }
  }}return cuts;
}
function addNormalWall(output:WallSpec[],ctx:DomainContext,cellX:number,cellZ:number,wall:TopologyWall,pillarCuts:readonly [number,number][]):void{const cuts=[...(wall.portal?[wall.portal]:[]),...wall.extraPortals].map(p=>[p.center-p.width/2,p.center+p.width/2] as [number,number]);for(const [a,b] of subtractIntervals(wall.start,wall.end,[...cuts,...pillarCuts]))pushClippedWall(output,ctx.seed,cellX,cellZ,wall.id,wall.runAxis,wall.fixed,a,b,WALL_HEIGHT/2,WALL_HEIGHT,wall.materialId);}
function nearPortal(wx:number,wz:number,p:TopologyPortal,wall:TopologyWall){return wall.runAxis==='x'?Math.abs(wz-wall.fixed)<1.2&&Math.abs(wx-p.center)<p.width/2+.9:Math.abs(wx-wall.fixed)<1.2&&Math.abs(wz-p.center)<p.width/2+.9;}
function addPillars(ctx:DomainContext,cellX:number,cellZ:number,allWalls:readonly TopologyWall[],out:PropSpec[]){const half=CELL_SIZE/2,cx=cellX*CELL_SIZE,cz=cellZ*CELL_SIZE,ox=unitFloat(`${ctx.seed}:gen3-pillar-offset:x`)*PILLAR_SPACING,oz=unitFloat(`${ctx.seed}:gen3-pillar-offset:z`)*PILLAR_SPACING;let count=0,deep=0;for(let gx=Math.floor((cx-half-ox)/PILLAR_SPACING)-1;gx<=Math.ceil((cx+half-ox)/PILLAR_SPACING)+1;gx++)for(let gz=Math.floor((cz-half-oz)/PILLAR_SPACING)-1;gz<=Math.ceil((cz+half-oz)/PILLAR_SPACING)+1;gz++){const wx=gx*PILLAR_SPACING+ox,wz=gz*PILLAR_SPACING+oz;if(wx<cx-half+.75||wx>cx+half-.75||wz<cz-half+.75||wz>cz+half-.75)continue;const inf=sampleGen3RegionInfluence(ctx.seed,wx,wz,ctx.worldDay,ctx.exposure,ctx.tuning);if(inf.arch>.28)continue;const key=`${gx}:${gz}`,ordinary=inf.pillar<.08;if(ordinary&&unitFloat(`${ctx.seed}:gen3-v4:ordinary-pillar:${key}`)>.018)continue;if(inf.pillarDepth>.78)deep++;const keep=ordinary?.8:clamp01(.015+inf.pillar*.08+inf.pillarDepth*.88+inf.deepPillar*.20+Math.max(unitFloat(`${ctx.seed}:row:${gz}`),unitFloat(`${ctx.seed}:col:${gx}`))*.05);if(unitFloat(`${ctx.seed}:gen3-v5:pillar:${key}`)>keep)continue;if(allWalls.some(w=>[...(w.portal?[w.portal]:[]),...w.extraPortals].some(p=>nearPortal(wx,wz,p,w))))continue;const size=PILLAR_MIN_WIDTH+unitFloat(`${ctx.seed}:gen3-pillar:${key}:size`)*(PILLAR_MAX_WIDTH-PILLAR_MIN_WIDTH);out.push({id:stableId('gen3-pillar',ctx.seed,key),kind:'column',position:{x:wx-cx,y:WALL_HEIGHT/2,z:wz-cz},scale:{x:size,y:WALL_HEIGHT,z:size},solid:true,materialId:'level-0-wallpaper'});count++;}return{count,deepSamples:deep};}
function relevantDomains(seed:string,cellX:number,cellZ:number){const cx=cellX*CELL_SIZE,cz=cellZ*CELL_SIZE,approxX=Math.floor(cx/(8.4*DOMAIN_MAJOR_SPANS)),approxZ=Math.floor(cz/(8.4*DOMAIN_MAJOR_SPANS)),half=CELL_SIZE/2,result:Array<{x:number;z:number}>=[];for(let dx=approxX-2;dx<=approxX+2;dx++)for(let dz=approxZ-2;dz<=approxZ+2;dz++){const b=domainWorldBounds(seed,dx,dz);if(b.maxX<cx-half-.5||b.minX>cx+half+.5||b.maxZ<cz-half-.5||b.minZ>cz+half+.5)continue;result.push({x:dx,z:dz});}return result;}
export function generateSpaceTopologyArchitecture(options:{seed:string;cellX:number;cellZ:number;worldDay:number;exposure:number;tuning:WorldTuning}):Gen3ArchitectureResult{const ctx:DomainContext={seed:options.seed,worldDay:options.worldDay,exposure:options.exposure,tuning:options.tuning},domains=relevantDomains(options.seed,options.cellX,options.cellZ),walls:WallSpec[]=[],props:PropSpec[]=[],topologyWalls:TopologyWall[]=[],archIds=new Set<string>();const half=CELL_SIZE/2,clip={minX:options.cellX*CELL_SIZE-half-.35,maxX:options.cellX*CELL_SIZE+half+.35,minZ:options.cellZ*CELL_SIZE-half-.35,maxZ:options.cellZ*CELL_SIZE+half+.35};for(const d of domains)topologyWalls.push(...generateTopologyDomainSlice(ctx,d.x,d.z,clip));
  const seamKeys=new Set<string>();for(const d of domains){seamKeys.add(`x:${d.x}:${d.z}`);seamKeys.add(`x:${d.x+1}:${d.z}`);seamKeys.add(`z:${d.z}:${d.x}`);seamKeys.add(`z:${d.z+1}:${d.x}`);}for(const key of seamKeys){const [axisRaw,lineRaw,alongRaw]=key.split(':');const s=topologySeamWall(ctx,axisRaw as 'x'|'z',Number(lineRaw),Number(alongRaw));if(!s.omitted)topologyWalls.push(s);}
  const unique=new Map<string,TopologyWall>();for(const w of topologyWalls)unique.set(w.id,w);const all=[...unique.values()];const pillar=addPillars(ctx,options.cellX,options.cellZ,all,props);for(const w of all){const cuts=[...pillarCutsForWall(options.cellX,options.cellZ,w,props),...portalLandingCuts(w,all)];if(w.arch){archIds.add(w.id);addArchWall(walls,ctx,options.cellX,options.cellZ,w,cuts);}else addNormalWall(walls,ctx,options.cellX,options.cellZ,w,cuts);}return{walls,props,archDividerIds:[...archIds].sort(),irregularArchDividerIds:[],pillarCount:pillar.count,deepPillarSamples:pillar.deepSamples};}
