import { clearObjectCatalogShowcase, spawnObjectCatalogEntries } from '../renderer/objectCatalog.js';
import { developmentContextForDesignTargetId, developmentContextForProp } from '../presentation/developmentContext.js';
import { semanticTargetForPropKind } from '../presentation/level0FeatureRepresentations.js';
import { clearAllPresentationPreviews, clearPresentationPreview, presentationPreviewParameters, presentationPreviewSnapshot, setPresentationPreviewBinding, setPresentationPreviewParameters } from '../presentation/previewOverrides.js';
import { representationId, semanticPresentationTargetId } from '../presentation/types.js';
import type { CellDescriptor, RegionId } from '../world/types.js';
import { WORLD_LAB_STUDIO_EVENT, type StudioBridgeCommand, type StudioRuntimeSnapshot, type WorldLabStudioAction } from './studioBridgeProtocol.js';

const STUDIO_ORIGIN='http://127.0.0.1:4311'; const POLL_MS=450;
interface StudioGameAccess{save?:{seed:string;generationVersion:string};currentCell?:CellDescriptor;camera?:{getPosition():{x:number;y:number;z:number}};updateStreaming(force?:boolean):void;locateRegion(regionId:RegionId):void;locateBlackout():void;locateHoleCluster():void;}
function showcaseId(targetId:string):string|undefined{if(targetId==='feature.medium-bucket')return'prop:bucket';if(targetId==='feature.small-grey-open-paint-can')return'prop:paint-can';}
function targetRegion(targetId:string):RegionId|undefined{if(targetId==='architecture.a-a1'||targetId==='feature.medium-bucket'||targetId==='feature.small-grey-open-paint-can'||targetId==='material.arch-pale-wallpaper')return'arch-rooms';if(targetId==='architecture.p-a1')return'pillar-field';if(targetId==='material.level-0-wallpaper'||targetId==='material.level-0-carpet'||targetId==='material.level-0-ceiling'||targetId==='material.fluorescent-panel')return'ordinary-level-0';}
async function bridgeFetch(path:string,token:string,init:RequestInit={}):Promise<Response>{return fetch(`${STUDIO_ORIGIN}${path}`,{...init,headers:{'Content-Type':'application/json','X-Noclip-Studio-Token':token,...(init.headers??{})}});}

export function installStudioBridgeClient(game:unknown):void{
  const token=import.meta.env.VITE_NOCLIP_STUDIO_TOKEN;if(!token){console.info('[Noclip Studio] bridge disabled; start with npm run studio to enable local authoring.');return;}
  const access=game as StudioGameAccess;const clientId=`game-${crypto.randomUUID()}`;let selectedTargetId='feature.medium-bucket';let lastCommand=0;let branchOrRef:string|undefined;let stopped=false;
  const refresh=():void=>access.updateStreaming(true);
  const context=()=>{const cell=access.currentCell;if(cell&&(selectedTargetId==='feature.medium-bucket'||selectedTargetId==='feature.small-grey-open-paint-can')){const prop=cell.props.find((candidate)=>semanticTargetForPropKind(candidate.kind)===selectedTargetId);if(prop)return developmentContextForProp(cell,prop,{branchOrRef,activePreviewOverrides:presentationPreviewParameters(semanticPresentationTargetId(selectedTargetId))});}return developmentContextForDesignTargetId(selectedTargetId,{branchOrRef,activePreviewOverrides:presentationPreviewParameters(semanticPresentationTargetId(selectedTargetId))});};
  const snapshot=():StudioRuntimeSnapshot=>{const cell=access.currentCell;const position=access.camera?.getPosition();return{clientId,connectedAt:new Date().toISOString(),selectedTargetId,seed:access.save?.seed,generationVersion:access.save?.generationVersion,regionId:cell?.world.regionId,conditionIds:cell?.world.conditionIds??[],cell:cell?{id:cell.id,x:cell.address.cellX,z:cell.address.cellZ}:undefined,playerPosition:position?{x:position.x,y:position.y,z:position.z}:undefined,developmentContext:context(),previewState:presentationPreviewSnapshot(),diagnostics:cell?[`runtime Cell ${cell.id}`,`props ${cell.props.length}`]:['journey not started']};};
  const applyCommand=(command:StudioBridgeCommand):void=>{if(command.targetId)selectedTargetId=command.targetId;const target=semanticPresentationTargetId(selectedTargetId);switch(command.type){case'select-target':case'focus-target':break;case'preview-parameters':if(command.payload?.parameters){setPresentationPreviewParameters(target,command.payload.parameters);refresh();}break;case'preview-binding':if(command.payload?.representationId){setPresentationPreviewBinding(target,representationId(command.payload.representationId));refresh();}break;case'clear-preview':clearPresentationPreview(target);refresh();break;case'clear-all-previews':clearAllPresentationPreviews();refresh();break;case'refresh-presentation':refresh();break;case'spawn-showcase':{const id=showcaseId(selectedTargetId);if(id)spawnObjectCatalogEntries([id]);break;}case'isolate-target':{clearObjectCatalogShowcase();const id=showcaseId(selectedTargetId);if(id)spawnObjectCatalogEntries([id]);else{const region=targetRegion(selectedTargetId);if(region)access.locateRegion(region);}break;}case'locate-target':{if(selectedTargetId==='condition.blackout')access.locateBlackout();else if(selectedTargetId==='carver.floor-hole-cluster')access.locateHoleCluster();else{const region=targetRegion(selectedTargetId);if(region)access.locateRegion(region);}break;}}};
  window.addEventListener(WORLD_LAB_STUDIO_EVENT,(event)=>{const action=(event as CustomEvent<WorldLabStudioAction>).detail;selectedTargetId=action.targetId;if(action.type==='isolate')applyCommand({id:lastCommand,type:'isolate-target',targetId:action.targetId});void bridgeFetch('/api/bridge/focus',token,{method:'POST',body:JSON.stringify({clientId,targetId:action.targetId})}).catch(()=>undefined);});
  const loop=async():Promise<void>=>{while(!stopped){try{const stateResponse=await bridgeFetch('/api/bridge/state',token,{method:'POST',body:JSON.stringify(snapshot())});if(stateResponse.ok){const reply=await stateResponse.json() as {branch?:string};branchOrRef=reply.branch??branchOrRef;}const commandsResponse=await bridgeFetch(`/api/bridge/commands?clientId=${encodeURIComponent(clientId)}&after=${lastCommand}`,token);if(commandsResponse.ok){const commands=await commandsResponse.json() as StudioBridgeCommand[];for(const command of commands){applyCommand(command);lastCommand=Math.max(lastCommand,command.id);}}}catch{}await new Promise((resolve)=>window.setTimeout(resolve,POLL_MS));}};
  void loop();window.addEventListener('pagehide',()=>{stopped=true;},{once:true});
}
